Feature/assignment exports
wri/fw_exports pull request #29
Opened 2022-11-08 23:51 UTC by edward3sc

New endpoint POST /exports/assignments/exportSome to export a selection of assignments

New endpoint POST /exports/assignments/exportAll to export all assignments user can see

2022-11-09 10:23 UTC, correcthorsebatterystaple requested changes

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/routes/v3/assignments.router.js
> +router.post("/exportSome", isAuthenticatedMiddleware, getAssignmentSet, AssignmentRouter.export);
```suggestion
router.post("/some", isAuthenticatedMiddleware, getAssignmentSet, AssignmentRouter.export);
```

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/routes/v3/assignments.router.js
> +router.post("/exportAll", isAuthenticatedMiddleware, getAllAssignments, AssignmentRouter.export);
```suggestion
router.post("/", isAuthenticatedMiddleware, getAllAssignments, AssignmentRouter.export);
```

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/routes/v3/assignments.router.js
> +    newURL.save();
```suggestion
    await newURL.save();
```

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/routes/v3/assignments.router.js
> +    newURL.save();
```suggestion
    await newURL.save();
```

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/routes/v3/assignments.router.js
> +    if (email) SparkpostService.sendMail(email, URL);
Does this not need to be awaited?

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/routes/v3/assignments.router.js
> +    }); */
```suggestion
```

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/routes/v3/assignments.router.js
> +  if (!user || !user.id) {
```suggestion
  if (!user.id) {
```
user will always be truthy

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/routes/v3/assignments.router.js
> +const exportFunction = async (id, payload, fields, fileType, email) => {
Add JSDoc and param types

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/routes/v3/assignments.router.js
> +      BucketURLModel.deleteMany({ id: id });
Does this not need to be awaited?

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/routes/v3/assignments.router.js
> +    else assignments.push(assignment);
```suggestion
    assignments.push(assignment);
```

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/routes/v3/assignments.router.js
> +router.post("/exportAll", isAuthenticatedMiddleware, getAllAssignments, AssignmentRouter.export);
Can we just merge the two endpoints and do the payload fetching the in the body of the endpoint instead of using middleware?

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/services/assignmentFile.service.js
> +  static async createBundle(payload) {
Add JSDoc and param types

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/services/assignmentFile.service.js
> +  static async createCsv(payload, requestedFields) {
Add JSDoc and param types

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/services/assignmentFile.service.js
> +  static async createShape(payload) {
Add JSDoc and param types

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/services/assignments.service.js
> +  static async getAllAssignments() {
Add JSDoc and param types

2022-11-09 10:23 UTC, correcthorsebatterystaple commented on app/src/routes/v3/assignments.router.js
> +const exportFunction = async (id, payload, fields, fileType, email) => {
Maybe a nicer name?

2022-11-10 15:58 UTC, edward3sc commented on app/src/routes/v3/assignments.router.js
> +router.post("/exportSome", isAuthenticatedMiddleware, getAssignmentSet, AssignmentRouter.export);
I'd like to keep the endpoints the same as the other two

2022-11-10 15:59 UTC, edward3sc commented on app/src/routes/v3/assignments.router.js
> +    if (email) SparkpostService.sendMail(email, URL);
No - we don't need to wait for it to finish sending before continuing

2022-11-10 16:28 UTC, correcthorsebatterystaple approved these changes

2022-11-10 16:35 UTC, merged